# switch on scintillation inside the TPC
/Xe/detector/setLXeScintillation false

# Make a giant cylindrical source
/Xe/gun/type Point
/Xe/gun/angtype iso
/Xe/gun/position 0. 0. 0. mm
#/Xe/gun/shape Cylinder
#/Xe/gun/halfz 1000 mm
#/Xe/gun/radius 1000 mm
#/Xe/gun/center 0 0 0. mm

# Confine the source to the LXe volume
/Xe/gun/confine LXe #GXe

#/Xe/gun/Xe131NeutrinoCaptureSource Be7High 216.086
/Xe/gun/Xe131NeutrinoCaptureSource N13 0.
